version: '3'
services:
  # lb:
  #   image: haproxy
  #   ports:
  #     - "8080:8080"
    # volumes:
    #   - ./haproxy/haproxy.cfg:/etc/haproxy
  micro1:
    build:
      context: ./micro1
    ports:
      - "3011:3011"
  micro2:
    build:
      context: ./micro2
    ports:
      - "3012:3012"
  envoy:
    image: envoyproxy/envoy:v1.18.3
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "3015:8080"
